### ISSUE TITLE
ping fail on new vr9 arv7519rw board

### ISSUE THREAD

**Issue by gmtii** [danielschwierzeck/u-boot-lantiq#1]
hi,

Ping fails when booting Openwrt from this u-boot on arv7519rw22 board (http://wiki.openwrt.org/toh/arcadyan/arv7519) (support added on this fork: https://github.com/gmtii/u-boot-lantiq/tree/openwrt/v2013.10

in u-boot:

U-Boot 2013.10-openwrt5-dirty (Jan 07 2014 - 10:29:58) arv7519rw

Board: Lantiq ARV7519RW VRX200 Family Board
SoC:   Lantiq VRX288 v1.2
CPU:   500 MHz
IO:    250 MHz
BUS:   250 MHz
BOOT:  NOR
DRAM:  128 MiB
Flash: 32 MiB
In:    serial
Out:   serial
Err:   serial
Net:   ltq-eth
Hit any key to stop autoboot:  0 
arv7519rw # ping 192.168.1.100
ltq_phy: addr 0, link 0, speed 10, duplex 0
ltq_phy: addr 17, link 0, speed 10, duplex 0
ltq_phy: addr 19, link 1, speed 100, duplex 1
Using ltq-eth device
host 192.168.1.100 is alive
arv7519rw # 

from Openwrt I can only ping host if payload is <15:

root@OpenWrt:/# ping -s 14 192.168.1.100
PING 192.168.1.100 (192.168.1.100): 14 data bytes
22 bytes from 192.168.1.100: seq=0 ttl=64 time=0.483 ms

Ping is ok in oem u-boot booting same Openwrt image, so it seems related to net hw initialization done by this u-boot .

Thank you very much.

**Comment by csharper2005** [comment]
> ARV7519 output complete log as default, and boot password was stored in clear text in boot dump :-)

Hi @gmtii ! Could you share a boot password with me?
