### ISSUE TITLE
config for easy80920 uboot

### ISSUE THREAD

**Issue by congallenwang** [danielschwierzeck/u-boot-lantiq#16]
hi Danial,

a beginner's question. how can i build uboot for EASY80920 board for openwrt? is there a config template or should i put it under openwrt build? thanks.

**Comment by danielschwierzeck** [comment]
# you need to set CROSS_COMPILE according to your toolchain, e.g.
$ export CROSS_COMPILE=~/.buildman-toolchains/gcc-4.9.0-nolibc/mips-linux/bin/mips-linux-

# switch to the most recent branch
$ git checkout openwrt/v2014.01-next

# configure for EASY80920 with NAND boot
$ make easy80920_nandspl_config
Configuring for easy80920_nandspl - Board: easy80920, Options: SYS_BOOT_NANDSPL

# then you can build
$ make -j8
