### ISSUE TITLE
P-2812HNU-F3 NOR support

### ISSUE THREAD

**Issue by ScApi** [danielschwierzeck/u-boot-lantiq#6]
I'm trying to build U-boot for this board, it's similar to P-2812HNU-F1/Fx, images created with v2014.04 branch works, asc/nand, but after adding NOR Boot support or only NOR with NAND stripped out, boot goes till DRAM: 128/256 prompt  (error in ddr config in Your branch) and goes back to UART mode, from what I see in similar boards there should be Flash prompt so I assume there is something wrong about My config, but even adding #CONFIG_LTQ_SUPPORT_NOR_FLASH is making this issue. Am I missing something ?

**Comment by vido89** [comment]
@ScApi I also find CFG 02 UART do you know for what is it ? Cant find 04 :(
